// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDW66thoLB_thNoVAtRBVFVZK44Ea0B4Y',
    appId: '1:366770963195:web:ee328de84f1e36a7dda65e',
    messagingSenderId: '366770963195',
    projectId: 'berealstep',
    authDomain: 'berealstep.firebaseapp.com',
    databaseURL: 'https://berealstep-default-rtdb.firebaseio.com',
    storageBucket: 'berealstep.appspot.com',
    measurementId: 'G-YNFG8MEWEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLNjsftwBio7xX3ddbiIgiFhZQgOMlBTY',
    appId: '1:366770963195:android:c7c07da7bf49a165dda65e',
    messagingSenderId: '366770963195',
    projectId: 'berealstep',
    databaseURL: 'https://berealstep-default-rtdb.firebaseio.com',
    storageBucket: 'berealstep.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGuEt_RlbpUYtx8hZ-2Fxpu3aRLR-TAcU',
    appId: '1:366770963195:ios:d2be2617d9555c30dda65e',
    messagingSenderId: '366770963195',
    projectId: 'berealstep',
    databaseURL: 'https://berealstep-default-rtdb.firebaseio.com',
    storageBucket: 'berealstep.appspot.com',
    iosBundleId: 'com.rebeal.clone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGuEt_RlbpUYtx8hZ-2Fxpu3aRLR-TAcU',
    appId: '1:366770963195:ios:d2be2617d9555c30dda65e',
    messagingSenderId: '366770963195',
    projectId: 'berealstep',
    databaseURL: 'https://berealstep-default-rtdb.firebaseio.com',
    storageBucket: 'berealstep.appspot.com',
    iosBundleId: 'com.rebeal.clone',
  );
}
